### ISSUE TITLE
shacl validation failure using deer:fromUri

### ISSUE THREAD

**Issue by ssilwal29** [dice-group/deer#26]
HI, I recently found out about this project and this has some really useful stuff and thank you for the project. I  was trying to use `deer:fromUri` to read triples using http, it fails on shacl validation. I was able to change locally and make it work removing 
https://github.com/dice-group/deer/blob/master/deer-core/src/main/resources/shacl/org.aksw.deer.io.SparqlModelReader.ttl#L25-L35
and 
https://github.com/dice-group/deer/blob/master/deer-core/src/main/resources/shacl/org.aksw.deer.io.SparqlModelWriter.ttl#L24-L34
Also updating to use https://github.com/dice-group/deer/blob/5e9352f06e732a970b39d9dca4df1f55d2b26053/deer-core/src/main/resources/shacl/org.aksw.deer.io.FileModelReader.ttl#L26 to use `xsd:string`, since the io expects it to be string like how it is for `deer:fromPath`

**Comment by kvndrsslr** [comment]
Hey, good that you have a use for our project!
It is expected that you pass URIs as URIs, not as strings.
`deer:fromPath` accepts strings as paths to local file system are not a subset of URIs.
For example, in Turtle, instead of `deer:fromUri "http://example.com"`, use `deer:fromUri <http://example.com>` and it will validate just fine.
